### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by jocelyn** [corvideon/awesome-eiffel#1]
- git mirror of the libraries included with EiffelStudio: https://github.com/eiffelsoftware/libraries
- official lib and more from the community available at https://iron.eiffel.com/  (for instance for 20.05 https://iron.eiffel.com/repository/20.05/package/ )
- Eiffel related repositories on github : https://github.com/search?l=Eiffel&q=eiffel&type=Repositories
- also you are missing Gobo Eiffel: http://www.gobosoft.com/eiffel/gobo/index.html

**Comment by seamus-brady** [comment]
Thanks @jocelyn :+1:  
Those have been added :)
